apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: quay-image
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:800f9957b184a30f0e13a9918fb4fe99c5e6ddc8@sha256:2e7d71acd0730e1c3e457829587a61699238e1054a3c4b0cda6ba2a6ca84cc31
          name: container-image
